services:
  magnetic-one:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - autogen_data:/autogen  # Persist AutoGen data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CHAT_COMPLETION_PROVIDER=${CHAT_COMPLETION_PROVIDER}
      - CHAT_COMPLETION_KWARGS_JSON=${CHAT_COMPLETION_KWARGS_JSON}
      - BING_API_KEY=${BING_API_KEY}
    user: appuser
    init: true
    restart: unless-stopped

volumes:
  autogen_data:  # Persistent volume for AutoGen data
